
spring:
  datasource:
    password: zz123456.ZZ
    url: jdbc:mysql://youxiu326.xin:3306/super_man?useUnicode=true&characterEncoding=utf8
    username: youxiu326
  redis:
    host: youxiu326.xin
  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: '#.##'
      template_exception_handler: debug
    suffix: .html

server:
  port: 8080

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml

# 日志输出路径，例如日志文件存放于 /Users/su/Desktop/java/pv/pv.log
# 过滤器记录日志参考简书：https://www.jianshu.com/p/350d26dea23f
logging:
  path: /Users/su/Desktop/java/
